// Package wttr provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package wttr

// CurrentCondition defines model for CurrentCondition.
type CurrentCondition struct {
	Humidity *string `json:"humidity,omitempty"`
	PrecipMM *string `json:"precipMM,omitempty"`
	TempC    *string `json:"temp_C,omitempty"`
}

// WttrResponse defines model for WttrResponse.
type WttrResponse struct {
	CurrentCondition *[]CurrentCondition `json:"current_condition,omitempty"`
}
