openapi: "3.0.0"
info:
  version: 1.0.0
  title: Open-Meteo API
components:
  schemas:
    ForecastResponse:
      type: object
      properties:
        latitude:
          type: number
        longitude:
          type: number
        elevation:
          type: number
        timezone:
          type: string
        utc_offset_seconds:
          type: number
        current:
          $ref: '#/components/schemas/CurrentWeather'
        daily:
          $ref: '#/components/schemas/DailyWeather'
        hourly:
          $ref: '#/components/schemas/HourlyWeather'
    CurrentWeather:
      type: object
      properties:
        temperature_2m:
          type: number
        relative_humidity_2m:
          type: number
        precipitation:
          type: number
        weather_code:
          type: number
    DailyWeather:
      type: object
      properties:
        time:
          type: array
          items:
            type: string
        weather_code:
          type: array
          items:
            type: number
        temperature_2m_max:
          type: array
          items:
            type: number
        temperature_2m_min:
          type: array
          items:
            type: number
    HourlyWeather:
      type: object
      properties:
        time:
          type: array
          items:
            type: string
        temperature_2m:
          type: array
          items:
            type: number
        weather_code:
          type: array
          items:
            type: number
paths:
  /v1/forecast:
    get:
      summary: Get weather forecast
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForecastResponse'